import NextAuthProvider from "@/providers/NextAuthProvider";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner';
import TanStackProvider from "@/providers/TanStackProvider";
import Layout from "@/components/Layout/Layout";
import axios from "axios";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: "autzon",
    template: "%s | autzon",
  },
  description: 'Generated by create next app',
}

axios.defaults.baseURL = process.env.NEXTAUTH_URL;


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id="body" className={`${inter.className} overflow-hidden`}>
        <NextAuthProvider>
          <TanStackProvider>
            <Layout>
              {children}
            </Layout>
          </TanStackProvider>
        </NextAuthProvider>
        <Toaster position="top-right" richColors visibleToasts={1}/>
      </body>
    </html>
  )
}